# Application name
spring.application.name=mockwise-backend

# Google OAuth2 client credentials
spring.security.oauth2.client.registration.google.client-id=80768006194-potf57c6tnf0hremjdaie2ggokusbtdc.apps.googleusercontent.com
spring.security.oauth2.client.registration.google.client-secret=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

# Redirect URI — should match exactly with the one set in Google Cloud Console
spring.security.oauth2.client.registration.google.redirect-uri={baseUrl}/login/oauth2/code/{registrationId}

# Scopes (profile and email)
spring.security.oauth2.client.registration.google.scope=openid,profile,email

# Google OAuth2 provider endpoints (not strictly necessary unless customizing)
spring.security.oauth2.client.provider.google.authorization-uri=https://accounts.google.com/o/oauth2/v2/auth
spring.security.oauth2.client.provider.google.token-uri=https://oauth2.googleapis.com/token
spring.security.oauth2.client.provider.google.user-info-uri=https://www.googleapis.com/oauth2/v3/userinfo
spring.security.oauth2.client.provider.google.user-name-attribute=sub

server.servlet.session.cookie.same-site=lax
server.servlet.session.cookie.secure=false

# Server port
server.port=8080

# --- PostgreSQL datasource ---
spring.datasource.url=jdbc:postgresql://localhost:5432/mockwise_db
spring.datasource.username=mockwise_user
spring.datasource.password=cricket2961999
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA/Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

# --- Mail settings (configure for your SMTP provider) ---
spring.mail.host=smtp.gmail.com
spring.mail.port=587
# spring.mail.port=${MAIL_PORT:1025}
spring.mail.username=intelligentinterviewplatform@gmail.com
spring.mail.password=lezhawofiojkvayv
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.starttls.required=true
spring.mail.properties.mail.smtp.ssl.trust=smtp.gmail.com

# Application base URL for verification links
app.base-url=http://localhost:8080
app.verification.expiry-hours=3
app.frontend-url=http://localhost:5173
app.password-reset.expiry-hours=3